import React from 'react';
import { Card } from '../common/Card';

interface Project {
  id: string;
  title: string;
  description: string;
  skills: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  estimatedHours: number;
  githubUrl?: string;
  liveUrl?: string;
  imageUrl?: string;
  startDate: string;
  endDate: string;
}

interface CVPreviewProps {
  studentName: string;
  studentEmail: string;
  studentBio?: string;
  projects: Project[];
  skills: string[];
}

export const CVPreview: React.FC<CVPreviewProps> = ({
  studentName,
  studentEmail,
  studentBio,
  projects,
  skills,
}) => {
  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('en-US', {
      month: 'short',
      year: 'numeric',
    });
  };

  return (
    <Card className="bg-white p-8 print:p-0 shadow-lg print:shadow-none">
      {/* Header */}
      <div className="border-b-2 border-gray-300 pb-6 mb-6">
        <h1 className="text-3xl font-bold text-gray-900">{studentName}</h1>
        <p className="text-gray-600 mb-2">{studentEmail}</p>
        {studentBio && <p className="text-sm text-gray-600">{studentBio}</p>}
      </div>

      {/* Summary Section */}
      {studentBio && (
        <div className="mb-6">
          <h2 className="text-lg font-bold text-gray-900 mb-2">About</h2>
          <p className="text-sm text-gray-700">{studentBio}</p>
        </div>
      )}

      {/* Skills Section */}
      {skills.length > 0 && (
        <div className="mb-6">
          <h2 className="text-lg font-bold text-gray-900 mb-2">Skills</h2>
          <div className="flex flex-wrap gap-2">
            {skills.map((skill) => (
              <span
                key={skill}
                className="inline-block px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm font-medium"
              >
                {skill}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Projects Section */}
      {projects.length > 0 && (
        <div className="mb-6">
          <h2 className="text-lg font-bold text-gray-900 mb-4">Projects</h2>
          <div className="space-y-4">
            {projects.map((project) => (
              <div key={project.id} className="border-l-4 border-green-600 pl-4 pb-4">
                <div className="flex items-center justify-between mb-1">
                  <h3 className="font-semibold text-gray-900">{project.title}</h3>
                  <span className="text-xs text-gray-600">
                    {formatDate(project.startDate)} - {formatDate(project.endDate)}
                  </span>
                </div>
                <p className="text-sm text-gray-700 mb-2">{project.description}</p>
                <div>
                  <p className="text-xs font-medium text-gray-600 mb-1">Technologies:</p>
                  <p className="text-xs text-gray-600">{project.skills.join(', ')}</p>
                </div>
                {(project.githubUrl || project.liveUrl) && (
                  <div className="mt-2 flex gap-2">
                    {project.githubUrl && (
                      <a
                        href={project.githubUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-green-600 hover:underline"
                      >
                        GitHub
                      </a>
                    )}
                    {project.liveUrl && (
                      <a
                        href={project.liveUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-green-600 hover:underline"
                      >
                        Live Demo
                      </a>
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="mt-8 pt-6 border-t border-gray-300 text-xs text-gray-500 text-center">
        <p>Generated by ORDO - AI-Powered Student Success Ecosystem</p>
      </div>
    </Card>
  );
};
